# Generated by Django 4.0.1 on 2022-02-07 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_tasklist_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Others', max_length=200),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.category'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='description',
            field=models.TextField(default='Others'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
