# Generated by Django 4.0.1 on 2022-02-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_category_name_alter_tasklist_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Others', max_length=200, unique=True),
        ),
    ]
